title: IT DevOps Blog
description: > # this means to ignore newlines until "baseurl:"
  This blog is my personal guide through DevOps development on different technologies and quick cheat-sheet of installation guidelines and commands. Enjoy! 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krzwiatrzyk.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Krzysztof Wiatrzyk # add your name
author-img: krzwiatrzyk.jpg # add your photo
about-author: I am an ICT student that wants to develop in DevOps direction. 
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: krzwiatrzyk # add your Github handle
social-linkedin: krzysztof-wiatrzyk-6538a514a
social-email: krzwiatrzyk@protonmail.com

# Disqus
discus-identifier: krzwiatrzyk # add your discus identifier

highlighter: rouge

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
